GreenmaskIO/greenmask

- internal/db/postgres/transformers/random_faker.go
- internal/db/postgres/transformers/real_address.go
- internal/db/postgres/transformers/real_address_test.go
**Description:**
I've made code changes to add support for the new transformers. This merge request aims to incorporate these changes into our project's codebase.
**Changes Made:**
- Added code implementations for the following transformers:
- RandomLatitude
- RandomLongitude
- RandomUnixTime
- RandomMonthName
- RandomYearString
- RandomDayOfWeek
- RandomDayOfMonth
- RandomCentury
- RandomTimezone
- RandomEmail
- RandomMacAddress
- RandomDomainName
- RandomURL
- RandomUsername
- RandomIPv4
- RandomIPv6
- RandomPassword
- RandomWord
- RandomSentence
- RandomParagraph
- RandomCCType
- RandomCCNumber
- RandomCurrency
- RandomAmountWithCurrency
- RandomTitleMale
- RandomTitleFemale
- RandomFirstName
- RandomFirstNameMale
- RandomFirstNameFemale
- RandomLastName
- RandomName
- …
> Feature: Added multiple faker transformers

- Makefile
- cmd/greenmask/main.go
- internal/db/postgres/pgcopy/row.go
- internal/db/postgres/pgcopy/row_test.go
- internal/db/postgres/pgdump/pgdump.go
This PR introduces a bug fixes:
* Fixed bug when raw COPY lines were parsed incorrectly #2 
* Fixed `--version` parameter behaviour
* Fixed `--dbname` parameter - now it correctly works with PostgreSQL connection string in URI format `postgresql:///`
> Greenmask v0.1.2 release

- internal/db/postgres/pgdump/pgdump.go
- internal/db/postgres/pgrestore/pgrestore.go
- internal/db/postgres/transformers/json.go
- internal/db/postgres/transformers/json_test.go
* Fixed Json transformer: previously it did not parse operation fields correctly. Closes issue #4 
* Fixed database connection string builder in pg_restore and pg_dump wrapper
> Json transformer and connection string fixes

- internal/db/postgres/transformers/cmd.go
- internal/db/postgres/transformers/hash.go
- internal/db/postgres/transformers/hash_test.go
- pkg/toolkit/parameter.go
* New `Hash` transformer uses `sha1` hash by default.
* Added parameter `function` that can provide a choice of possible hash algorithms `md5, sha1, sha256, sha512`.
* Added `max_length` parameter allowing to truncate hash tail higher than provided length. The default value is `0` - meaning "do not truncate"
* Fixed metadata enrichment for validation warnings caused by `RawValueValidator`
**Example:**
```yaml
- schema: "humanresources"
name: "employee"
transformers:
- name: "Hash"
params:
column: "loginid"
function: "sha1"
max_length: 10
```
Additional changes:
* Added Error severity for Cmd parameter validator
Closes #8
> New Hash transformer implementation and validation warning fixes

- cmd/greenmask/cmd/dump/dump.go
- cmd/greenmask/cmd/list_dumps/list_dumps.go
- cmd/greenmask/cmd/list_transformers/list_transformers.go
- cmd/greenmask/cmd/restore/restore.go
- cmd/greenmask/cmd/root.go
- cmd/greenmask/cmd/show_transformer/show_transformer.go
- internal/db/postgres/transformers/cmd.go
- internal/db/postgres/transformers/real_address.go
- pkg/toolkit/parameter.go
- tests/integration/toc/backward_compatibility_test.go
**Command interface improvements**
* Introduced temporal solution for Column container. Greenmask has a few transformers with parameters that are lists of objects that point out on the columns of the table. For correct `list-transformers` and `show-transformer` command print the `IsColumnContainer` property is introduced. This later will raise the feature implementation task for "Container" parameters introspection.
* Reduced output in list-transformers command. Now it prints only the transformer name, description, and column parameters
* Added `show-transformer` command that prints details about transformer found by name provided
* Fixed `list-dump`, `list-transformers`, and `restore` commands exit code on error
* Refactored code
> Command interface improvements

- cmd/greenmask/cmd/validate/validate.go
- internal/db/postgres/cmd/dump.go
- internal/db/postgres/cmd/validate.go
- internal/db/postgres/context/context.go
- internal/db/postgres/context/pg_catalog.go
- internal/db/postgres/context/pg_catalog_test.go
- internal/db/postgres/context/schema.go
- internal/db/postgres/storage/metadata_json.go
- internal/domains/config.go
- pkg/toolkit/database_schema.go
- pkg/toolkit/table.go
Implemented previous dump diff.
The dump diff may raise the next change events:
- TableMovedToAnotherSchema
- TableRenamed
- TableCreated
- ColumnCreated
- ColumnRenamed
- ColumnTypeChanged
The column removal and table removal are not checked because the data leakage may be caused only by new columns and new tables
> Validate schema diff

- internal/db/postgres/cmd/restore.go
- internal/db/postgres/cmd/show_dump.go
- internal/db/postgres/toc/entry.go
- internal/db/postgres/toc/header.go
- internal/db/postgres/toc/toc.go
- internal/utils/cmd_runner/cmd_runner.go
* Implemented `--exit-on-error` parameter for pg_restore run. But it does not play for "data" section restoration now. If any error is caused in "data" section - greenmask exits with the error
* Fixed dependant objects dropping when running with `--clean` parameter
* Fixed `show-dump` command in text mode
> restore and show-dump command fixes

- docs/configuration.md
While I was exploring the repository code, I noticed that there are some environment variables configuration available that are undocumented.
Using environment variables for configuration is extremely useful, specially when running Greenmask as a Job inside a cluster.
I also would like to suggest the addition of some other environment variables that could improve ease configuration:
- Storage
- `TYPE` - chose storage type, valid values are `directory` or `s3`
- `BUCKET_NAME`
- `BUCKET_REGION` - recently the possibility to set the region through the `AWS_REGION` environment variable was added, but adding this additional variable would align for a more cohesive env var naming
- `PATH` - for `directory` storage, but this could also be used as `prefix` when using `s3` storage
Other variables …
> Add environment variable section to the configuration docs

- docs/configuration.md
- internal/storages/s3/config.go
- internal/storages/s3/s3.go
Fixed region value provided via environment variable `AWS_REGION` for s3 storage
Found when investigated #36
> Fixed s3 region env variable providing

- internal/storages/builder/builder.go
- internal/storages/s3/config.go
- playground/config.yml
* Fixed S3 storage
* Deleted Validate method
* Fixed playground config.yml
> Fixed broken S3 storage after structure refactoring

- internal/db/postgres/context/context.go
- internal/db/postgres/context/pg_catalog.go
- internal/db/postgres/context/queries.go
- internal/db/postgres/entries/table.go
- pkg/toolkit/table.go
* Added tables scoring according to their size and transformation count. It should help to distribute the dumper tasks equally to the workers (#50). The transformer score is 0.03 for table size
* Fixed pgx rows object leakage during the schema introspection stage
> Table size and transformation scoring

- Makefile
- cmd/greenmask/cmd/root.go
- internal/storages/s3/config.go
- Introduces build flag to dynamically unmarshall environment variables to `Config`
closes #48
> dinamically map and bind env vars

- internal/storages/s3/s3.go
Current implementation is duplicating the bucket name in the object path prefix:
This PR removes the bucket name from the prefix, which was being unnecessarily added.
As a suggestion: I was thinking further on this and it would be nice to have a default path prefix definition that includes the db host and db name to avoid confusion in case one just decides to dump multiple database dumps into the same bucket without defining a prefix.
Something like:
`STORAGE_S3_PREFIX / DB_HOSTNAME-DB_NAME / DUMP_ID`
Where it would be possible to set another config value (ie. `STORAGE_S3_PATH` or some other naming to avoid confusion) to override the `DB_HOSTNAME-DB_NAME` string.
This would result in:
- defining only the bucket would "just work" with logical separation of multiple databases in the same …
> Remove bucket name from object path prefix

- docker/greenmask/Dockerfile
- Changes Dockerfile `WORKDIR` to `/home/greenmask`
Found this minor issue while testing
> change docker workdir to greenmask home

- internal/db/postgres/context/pg_catalog.go
The table's calculation size now is `pg_relation_size(oid) + pg_relation_size(reltoastrelid)`. We would use `pg_relation_size` but we need to exclude index size because we dump only the index DLL statement.
Resolves #50
> Adapted table size calculation with TOAST.

- cmd/greenmask/cmd/root.go
- internal/domains/config.go
- internal/utils/config/viper_workaround.go
This solves the problem with the map structure described -> https://github.com/spf13/viper/issues/373 that caused the issue in Greenmask #76
We need to keep the original keys in the map without lowercasing. To overcome this problem we need to use default `yaml` and `json` parsers to avoid viper or mapstructure usage
The related viper [issue](https://github.com/spf13/viper/issues/373)
> Fix: viper and mapstructure limitation workaround

- internal/db/postgres/cmd/dump.go
Fixes doubled TOC entries when dumping only schema without data
> fix: Fixed wrong behavior of schema and data toc entries merge

- docker/integration/tests/Dockerfile
Fix CI/CD integration test job:
* added condition for exiting the integration test launch script
> Added a condition for exiting the integration test launch script

- internal/db/postgres/transformers/noise_date.go
- internal/db/postgres/transformers/random_date.go
* Set `max_ratio` required
* Added info about default values
* Fixed truncate parameter validator
> fix: Fixes in NoiseData transformer

- internal/db/postgres/transformers/noise_numeric.go
- internal/db/postgres/transformers/random_numeric.go
- internal/generators/transformers/noise_numeric.go
- internal/generators/transformers/random_numeric.go
- internal/generators/transformers/random_numeric_test.go
* Fixed limiters
* Refactored Transform method signature - ctx replaced with strict pointer on the Type
* Fixed tests
* Added getNoiseNumericLimiterForDynamicParameter function
* Added `SetDynamicLimiter` method that replaces passing the limiter object via context
> fix: Fixed NoiseNumeric and RandomNumeric limiters

- internal/db/postgres/transformers/random_mac.go
- internal/db/postgres/transformers/random_mac_test.go
- internal/db/postgres/transformers/tesing_helpers_test.go
- internal/generators/transformers/random_mac.go
- internal/generators/transformers/random_mac_test.go
* Replaced logic from manual parsing to net.HardwareAddr object
* Revised encode-decoding logic via driver
* Revised tests and renamed some functions
> fix: Revised RandomMac transformer

- internal/db/postgres/cmd/dump.go
We do not need to manage transactions in case of validation - we just close the connection. According to the documentation, the client can interrupt the COPY stream via connection close. Before this fix it raised a deadlock.
> fix: Fixed transaction rollback in validate command

- internal/db/postgres/transformers/random_person.go
Fixed case when hashing value is not set for each column in `RandomPerson` transformer
> fix: RandomPerson fix

- docs/database_subset.md
refreshed subset doc according to the latest changes
> doc: refreshed subset doc according the latest changes

- cmd/greenmask/cmd/restore/restore.go
- docs/commands/restore.md
- internal/db/postgres/cmd/restore.go
- internal/db/postgres/cmd/validate.go
- internal/db/postgres/pgrestore/pgrestore.go
- internal/db/postgres/restorers/table.go
- internal/db/postgres/restorers/table_insert_format.go
- internal/db/postgres/transformers/custom/dynamic_definition.go
- internal/db/postgres/transformers/utils/cmd_transformer_base.go
- internal/utils/cmd_runner/cmd_runner.go
- internal/utils/reader/reader.go
* Introduced the --batch-size flag for the restore command.
* The COPY command will complete after reaching the specified batch size, allowing for transaction state checks.
* The transaction spans across all batches.
* If an error occurs in any batch, all previous batches will be rolled back.
> feat: restore data in batches

- internal/db/postgres/context/pg_catalog.go
- internal/db/postgres/context/table.go
- pkg/toolkit/column.go
- pkg/toolkit/driver.go
- pkg/toolkit/meta.go
- pkg/toolkit/static_parameter.go
fixed case when the overridden type of column does not work
> fix: fixed case when the overridden type of column does not work

- cmd/greenmask/cmd/root.go
- internal/domains/config.go
Now if user provides the unknown key the error will be thrown
Closes #176
> fix: added error unused decoder setting

- internal/db/postgres/entries/table.go
fixed COPY restoration statement string (added semicolon and new line)
Closes #179
> fix: fixed COPY restoration statement string

- docs/database_subset.md
- internal/db/postgres/subset/component.go
- internal/db/postgres/subset/cte.go
- internal/db/postgres/subset/cycle_edge.go
- internal/db/postgres/subset/graph.go
* Added support for multi-cycles in the same strongly connected component
* It supports only cases where only one group of cycles (grouped by vertexes (tables)) is found
Closes #155
> feat: Subset stage 4: Multi cycles in the same SCC

- cmd/greenmask/cmd/restore/restore.go
- docker/integration/filldb/.dockerignore
- docker/integration/filldb/Dockerfile
- docker/integration/filldb/filldb.sh
- docker/integration/filldb/generated.sql
- docs/commands/restore.md
- internal/db/postgres/cmd/dump.go
- internal/db/postgres/cmd/restore.go
- internal/db/postgres/context/pg_catalog.go
- internal/db/postgres/context/schema.go
- internal/db/postgres/context/table.go
- internal/db/postgres/entries/table.go
- internal/db/postgres/pgrestore/pgrestore.go
- internal/db/postgres/restorers/table_insert_format.go
- internal/db/postgres/storage/metadata_json.go
- tests/integration/greenmask/backward_compatibility_test.go
* Added attributes for metadata handling.
* The restore command now retrieves table definitions from metadata in storage.
* introduced a new option for `restore` command `--overriding-system-value`. if `--inserts` option is provided generates `INSERT` statements with ` OVERRIDING SYSTEM VALUE VALUES`
* Generated columns in `toolkit.Table` are now excluded from the Columns list
* Grouped imports
* Added integration test for generated columns
Closes #183
Co-authored-by: @vinnyjth
> fix: Dump/Restore fails when masking tables with a generated column

- README.md
- docs/database_subset.md
- docs/index.md
- internal/db/postgres/cmd/dump.go
- internal/db/postgres/cmd/validate.go
- internal/db/postgres/context/context.go
- internal/db/postgres/context/virtual_references.go
- internal/db/postgres/subset/component.go
- internal/db/postgres/subset/component_link.go
- internal/db/postgres/subset/graph.go
- internal/db/postgres/subset/query.go
- internal/db/postgres/subset/table_link.go
- internal/domains/config.go
- internal/domains/virtual_references.go
* Introduced `virtual_references` that can be used to define logical foreign keys using column names or SQL expression
* Refactored subset system and removed artifacts
* Added subset query debugging in log-level=debug
* Implemented virtual reference validation
Closes #156
> feat: Subset stage 5: Virtual foreign keys

- cmd/greenmask/cmd/dump/dump.go
- cmd/greenmask/cmd/restore/restore.go
- docker-compose-integration.yml
- docker/greenmask/Dockerfile
- docker/integration/tests/Dockerfile
- internal/db/postgres/toc/entry.go
- internal/db/postgres/toc/reader.go
- internal/db/postgres/toc/utils.go
- internal/db/postgres/toc/writer.go
- tests/integration/greenmask/backward_compatibility_test.go
* Revised TOC Reader and Writer
* Added PG17 into integration tests
* Implemented integration tests more verbose
* Fixed --no-owner and --schema-only flags definition
Closes #152
> feat: Postgresql17 support

- playground/config.yml
running the playground currently causes the following error:
```
ERR ValidationWarning={"hash":"300b59e1e8f328f868bd32b03c1af0f0","meta":{"ParameterName":"max_ratio","SchemaName":"humanresources","TableName":"employee","TransformerName":"NoiseDate"},"msg":"parameter is required","severity":"error"}
2024-10-22T06:25:13Z FTL error="fatal validation error"
```
this change follows the required params as per the [docs](https://docs.greenmask.io/latest/built_in_transformers/standard_transformers/noise_date/#parameters)
> fix `fatal validation error` in playground

- docs/built_in_transformers/transformation_inheritance.md
- internal/db/postgres/cmd/dump.go
- internal/db/postgres/cmd/restore.go
- internal/db/postgres/context/config_builder.go
- internal/db/postgres/context/schema.go
- internal/db/postgres/restorers/table_insert_format.go
- pkg/toolkit/table.go
Closes #238
* Resolved an issue where `Dump.createTocEntries` processed partitioned tables as if they were physical entities, despite being logical.
* Refined the `findPartitionsOfPartitionedTable` function for improved accuracy.
* Corrected merging in the pre-data, data, and post-data sections, which previously caused a panic in dump command when the post-data section was excluded.
* Added metadata about the first parent root table in the `toolkit.Table` struct.
* Updated database schema metadata to include a root partition, which is necessary for performing `--inserts` during restoration.
* Fixed an issue where dumps created with `--load-via-partition-root` did not use the root partition table in `--inserts` generation during restoration.
* Revised a documentation example to ensure it …
> Fix: Addressed bugs related to partitioned tables

- internal/db/postgres/transformers/column_context.go
- internal/db/postgres/transformers/email.go
- internal/db/postgres/transformers/json_context.go
- internal/db/postgres/transformers/template_record_test.go
- pkg/toolkit/dynamic_parameter.go
- pkg/toolkit/expr.go
- pkg/toolkit/template_record_context.go
Closes #238
* Renamed methods according to the documentation: `GetColumnRawValue` is now `GetRawColumnValue`, and `SetColumnRawValue` is now `SetRawColumnValue`.
> Fix: Corrected naming in template context objects

- internal/db/postgres/context/config_builder.go
- internal/db/postgres/context/config_builder_test.go
- internal/db/postgres/context/context.go
- internal/db/postgres/context/context_test.go
Closes #244
- Fixed an issue where the table graph used a shared tables list, which was later sorted by the table size scoring function.
- Added a regression test for RuntimeContext to ensure proper functionality.
- Deleted commented code
> fix: resolve issue with shared tables list in table graph

- pkg/toolkit/types.go
I was trying Greenmask on a more complex DB (musicbrainz) and it was crashing in this code. It seems that the issue is that when silent is true, the type is not actually skipped.
I opened a PR directly in case it's this simple, but if you'd rather have me open an issue instead, I'm happy to.
> Fix skipping unknown type when silent is true

- cmd/greenmask/cmd/dump/dump.go
- cmd/greenmask/cmd/restore/restore.go
- docs/commands/dump.md
- docs/commands/restore.md
- go.mod
- internal/db/postgres/cmd/restore.go
- internal/db/postgres/pgdump/adapter.go
- internal/db/postgres/pgdump/pgdump.go
- internal/db/postgres/pgrestore/pgrestore.go
- internal/db/postgres/restorers/base.go
- internal/db/postgres/restorers/base_test.go
- internal/db/postgres/restorers/blobs.go
- internal/db/postgres/restorers/restorer.go
- internal/db/postgres/restorers/table.go
- internal/db/postgres/restorers/table_insert_format.go
- internal/db/postgres/restorers/table_insert_format_test.go
- internal/db/postgres/restorers/table_test.go
- internal/utils/ioutils/gzip_reader.go
- internal/utils/ioutils/gzip_reader_test.go
- internal/utils/ioutils/gzip_writer.go
- internal/utils/ioutils/gzip_writer_test.go
- internal/utils/testutils/containers.go
- internal/utils/testutils/storage.go
Closes #228 
* Implemented --disable-triggers - disables triggers on the restoring table
* Implemented --use-session-replication-role-replica - kind of workaround option for AWS RDS
* Implemented --superuser - uses superuser role provided to disable tigers or set session-replication-role to replica
* Refactored TableRestorer and TableRestorerInsertFormat - implemented restoreBase struct that embeds with base functionality.
* Implemented suite test helpers that provides base functionality to PG container in unit tests
* Added simple storage mock
* Covered Table restorers with tests
> feat: Disable triggers options

- internal/db/postgres/pgdump/pgdump.go
- internal/db/postgres/pgrestore/pgrestore.go
Some tools spit out a connection URL with a `postgres://`, not `postgresql://`. It's useful to be able to support both, as `pg_dump` and `pg_restore` do.
> Support postgres:// schema connection URLs

- internal/db/postgres/transformers/random_company.go
- internal/db/postgres/transformers/random_person.go
- internal/db/postgres/transformers/template_record.go
`SetIsColumnContainer(true)` for strutural column-like parameters
> fix: set lost ColumnContainer value for columns parameters

- .github/workflows/tests.yml
- Makefile
- docker-compose-integration.yml
- internal/db/postgres/transformers/utils.go
- internal/db/postgres/transformers/utils_test.go
Changes:
* Fixed global salt usage from context - now it correctly gets salt for generator. Covered by unit tests.
* Fixed github actions and docker compose for integration testings
* Added `make integration` target to run integration tests locally
Closes #317
> Fix: set global salt from context

- cmd/greenmask/cmd/dump/dump.go
- cmd/greenmask/cmd/list_dumps/list_dumps.go
- docs/commands/dump.md
- docs/commands/list-dumps.md
- internal/db/postgres/cmd/dump.go
- internal/db/postgres/pgdump/pgdump.go
- internal/db/postgres/storage/metadata_json.go
**Problem**
Dump IDs are not human-friendly, and over time it becomes hard to remember the purpose of each dump.
**Proposed Solution**
Add a `--description` flag to the dump command, store it in metadata, and display it in `list_dumps` for better context.
> feature: Add description option to dump command and include in metadata

- .gitignore
- cmd/greenmask/cmd/list_dumps/list_dumps.go
- docs/commands/list-dumps.md
Hi there,
Added a `-q` (quiet) option to the `list-dumps` command, similar to `docker ps -q`.
This makes it easy to use `list-dumps` in shell pipelines like:
`greenmask list-dumps -q | xargs -I {} greenmask delete {}`
> feature add --quiet to print only dump IDs
