GreenmaskIO/greenmask

- internal/db/postgres/pgdump/pgdump.go
- internal/db/postgres/pgrestore/pgrestore.go
Closes #6
Fixes `--user`, `--dbname`, `--host` and `--port` parameters utilization
> Fixed GetPgDSN behaviour

- docker-compose.yml
- playground/cleanup.sh
* Fixed playground environment variables and the `cleanup` command.
* Removed `start_period` not required property from `playground-storage`.
> Playground fixes

- internal/db/postgres/transformers/masking.go
- internal/db/postgres/transformers/utils/template/functions.go
Fixed `credit_card` parameter value for `type` parameter in `Masking` transformer
> Fix: fixed credit_card variable

- docs/built_in_transformers/standard_transformers/hash.md
- internal/db/postgres/transformers/hash.go
- pkg/toolkit/parameter.go
* Added `GREENMASK_GLOBAL_SALT` variable that might be used in the parameter
* Added sha3 functions support
> Improved Hash transformer

- internal/db/postgres/transformers/utils/transformation_funcs.go
- internal/db/postgres/transformers/utils/transformation_funcs_test.go
> Fixed panic caused in the RandomString transformer

- internal/db/postgres/context/context.go
- internal/db/postgres/context/pg_catalog.go
- internal/db/postgres/context/queries.go
- internal/db/postgres/context/schema.go
- internal/db/postgres/context/table.go
- internal/db/postgres/entries/table.go
- pkg/toolkit/column.go
* Added column attgenerated introspection for pg >= 12 version
* Excluded generated columns from COPY stmnt
Closes  #77
> fix: Fixed generated columns dumping and restoration #77

- .github/workflows/ci.yml
Change version of Python suitable for installation on Debian
> Fix CI/CD deploy-docs job

- internal/db/postgres/cmd/restore.go
Fixed restore command failure due to connection idle timeout #75
> fix: restore fails due to connection idle timeout

- tests/integration/storages/s3_test.go
fix: Fixed integration test for s3 storage
> fix: Fixed integration test for s3 storage

- internal/db/postgres/dumpers/large_object.go
> fix: fixed large object dumper panic caused by wrong function enclosure

- internal/db/postgres/context/table.go
- pkg/toolkit/column.go
- pkg/toolkit/static_parameter.go
* Added GetType for Column object
* Revised GetColumnSize - added OverriddenTypeSize
* Fixed logic in static_parameter.go
> doc: Fixed overridden_column_type logic

- docs/built_in_transformers/parameters_templating.md
- internal/db/postgres/transformers/dict.go
- internal/db/postgres/transformers/noise_date.go
- internal/db/postgres/transformers/noise_float.go
- internal/db/postgres/transformers/noise_int.go
- internal/db/postgres/transformers/noise_numeric.go
- internal/db/postgres/transformers/random_date.go
- internal/db/postgres/transformers/random_float.go
- internal/db/postgres/transformers/random_int.go
- internal/db/postgres/transformers/random_ip.go
- internal/db/postgres/transformers/random_mac.go
- internal/db/postgres/transformers/random_numeric.go
- internal/db/postgres/transformers/random_person.go
- internal/db/postgres/transformers/random_string.go
- internal/db/postgres/transformers/random_unix_timestamp.go
- mkdocs.yml
- pkg/toolkit/static_parameter.go
* Introduced static parameters value template
* Added doc
* Revised transformer and turned on templating mode where it is safe
> feat: Introduced static parameters value template

- internal/db/postgres/cmd/validate.go
> fix: Fixed returned schema and table name order in parseTableName

- docs/commands.md
> Tiny typo fix

- docs/built_in_transformers/standard_transformers/random_person.md
- internal/db/postgres/transformers/random_person.go
- internal/db/postgres/transformers/random_person_test.go
feat: Introduced keep_null parameter for columns in RandomPerson transformer
> feat: Introduced keep_null parameter for RandomPerson

- internal/db/postgres/transformers/noise_date_test.go
- internal/db/postgres/transformers/noise_float.go
- internal/db/postgres/transformers/noise_float_test.go
- internal/db/postgres/transformers/noise_int.go
- internal/db/postgres/transformers/noise_int_test.go
- internal/db/postgres/transformers/noise_numeric.go
- internal/db/postgres/transformers/noise_numeric_test.go
- internal/db/postgres/transformers/random_float.go
- internal/db/postgres/transformers/random_float_test.go
- internal/db/postgres/transformers/random_int.go
- internal/db/postgres/transformers/random_int_test.go
- internal/db/postgres/transformers/random_numeric.go
- internal/db/postgres/transformers/random_numeric_test.go
* fixed case when the min and max thresholds provided were ignored
Closes #176
> fix: fixed transformers threshold validation

- docs/installation.md
> doc: Revised installation section of doc

- docs/database_subset.md
- internal/db/postgres/context/virtual_references.go
- internal/db/postgres/subset/component.go
- internal/db/postgres/subset/condenced_edge.go
- internal/db/postgres/subset/graph.go
- internal/db/postgres/subset/query.go
- internal/db/postgres/subset/table_link.go
- internal/domains/virtual_references.go
- mkdocs.yml
* Introduced polymorphic_exprs attribute in virtual_references that allows to define the polymorphic condition for joining a parent table
* Revised doc and added subset usage for polymorphic references
Closes #198
> feat: Advanced subset: Polymorphic relationships

- .github/workflows/build.yml
- .github/workflows/docs.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- .github/workflows/update_dev_docs.yml
> #213 add golangci-lint job to pull request check

- docs/overrides/main.html
- docs/release_notes/greenmask_0_2_5.md
- internal/db/postgres/context/context.go
- internal/db/postgres/context/context_test.go
- mkdocs.yml
A problems appears after RuntimeContext refactoring in v0.2.1
Covered with regression
> docs: added v0.2.4 release notes

- internal/db/postgres/transformers/email.go
- internal/db/postgres/transformers/masking.go
- internal/db/postgres/transformers/random_faker.go
- internal/db/postgres/transformers/random_ip.go
- internal/db/postgres/transformers/random_mac.go
- internal/db/postgres/transformers/random_person.go
- internal/db/postgres/transformers/random_string.go
- internal/db/postgres/transformers/random_uuid.go
- internal/db/postgres/transformers/regexp_replace.go
> feat: Allowed all textual types for transformers

- docs/built_in_transformers/standard_transformers/index.md
- docs/built_in_transformers/standard_transformers/random_company.md
- mkdocs.yml
create missing documentation for RandomCompany transformer
> add documentation for random company

- internal/db/postgres/context/pg_catalog.go
- internal/db/postgres/toc/reader.go
- internal/db/postgres/toc/writer.go
* Removed unused buffer
* Fixed Oid type (now it is uint32)
* Revised getTables function
Closes #284
> Fixed type of Oid in TOC archive library

- docs/commands/index.md
- docs/configuration.md
> Doc: Revised log level value in doc

- docs/built_in_transformers/standard_transformers/replace.md
- internal/db/postgres/transformers/random_date.go
- internal/db/postgres/transformers/replace.go
- internal/db/postgres/transformers/replace_test.go
- pkg/toolkit/parameter_definition.go
* Implemented dynamic mode for value parameter
* Set column parameter as nullable
* Fixed comments typos
* Revised redundant code in random_date.go
Closes #292
> Feat: Dynamic parameters for Replace transformer

- internal/db/postgres/transformers/random_date.go
Just missed transformers.MinuteTruncateName at truncateParts array, fix that
> Fix for #297 issue
